name: Build and Deploy

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download necessary data files
        run: |
          wget -O MaterialExcelConfigData.json https://gitlab.com/Dimbreath/AnimeGameData/-/raw/master/ExcelBinOutput/MaterialExcelConfigData.json?ref_type=heads
          wget -O BuffExcelConfigData.json https://gitlab.com/Dimbreath/AnimeGameData/-/raw/master/ExcelBinOutput/BuffExcelConfigData.json?ref_type=heads
          wget -O ItemAbilities.json https://gitlab.com/Dimbreath/AnimeGameData/-/raw/master/BinOutput/Ability/Temp/ItemAbilities.json?ref_type=heads
          wget -O TextMapEN.json https://gitlab.com/Dimbreath/AnimeGameData/-/raw/master/TextMap/TextMapEN.json?ref_type=heads

      - name: Build metadata file
        run: |
          python main.py
      
      - name: Remove intermediate data files
        run: |
          rm MaterialExcelConfigData.json
          rm BuffExcelConfigData.json
          rm ItemAbilities.json
          rm TextMapEN.json
      
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
